### PR TITLE
Added Neural Net mode

### PR DESCRIPTION
**Pull request by akatzmann**
Added a new neural network mode, implementing a basic TD-Neural-Q-Learning algorithm.

### CODE REVIEW

**Comment by cpetry** [comment]
Wow this looks like quite some work.
Why though an extra antController?
Shouldn't the user himself code his ants?
If we add a complete neural network for the user there wouldnt be anthing left to do for him. Shouldn't everyone try to find the best code dir himself?

**Comment by akatzmann** [comment]
He should. This class is meant as an example of how to do this. As provided by code comments, this network script is far away of being perfect. More it is meant as a starting point of a simple Reinforcement-Solution, which can be extended by reweighting, rechosing network architecture, balancing rewards and improve by further developments like (Dynamic) Time Window, Sensory Control and Input, Output Coding and -Topology, etc.. To keep it short, there is still lots do for a real solution, which still would be far away from having the user nothing left to do. 
However, from my point of view this class should successively be outsourced to a special example class - which of course could be a basis for user developments. Actually, I see no big difference to the AntControllerSimple class here, except the function mechanism itself.
Arguing on code cleanity, I would expect the drop-down field for chosing a base implementation as gone in future versions. Especially, since for adding a competitive online mode I see adding different hives having different AntController-classes (or at least entities or specializations) as a one very major goal of AntSim. Of course, I see this as my personal contribution to an AntController-like class also.

**Comment by cpetry** [comment]
Ah okay.
As I am no neural network specialist I thought that this would be an almighty solution to be simply used without knowledge.
Thanks that you clearified this. I also wanted to add a "training mode" to be able to let several hundreds of simulations train (un)supervised learninging algorithms.
I will now try to learn and understand your code before merging.

**Comment by akatzmann** [comment]
Actually I'm still struggeling with closing the pull request, since the code does not look too nice and trunk should be kept clean as far as possible. 2 to 4 commits could possibly fix this (especially by erasing global functions, variables and so on). I'm just fearing to lose motivation to keep code clean when nobody has to work with it but me. ;-)
Say a word, bro!

**Comment by cpetry** [comment]
Weeeell if you would manage to create a well documented example code and a good base to work with, I believe I would be able to learn about it and create my own type of neural network ant.
Not only me but several other people coming into contact with this project could benefit from a well defined base. 😀 Be so kind and give it some more polishing.

**Comment by cpetry** [comment]
As you can see I restructured the neural network stuff.
Now the network itself is created before a simulation (or can be read from a JSON string/file)
Then when using an AntControllerNeuralNet the network is used (now inside settings).
No more globals, no require.
Also there is now a "training environment" where you can train whatever you want and test it.
For neural networks the "shouldTrain" variable is simply set or unset.

Please look over it and enhance if you want

**Pull request merged**
